# name: thoughtworksarts.io
# url: 'https://thoughtworksarts.io'
name: twa-test.github.io
url: "https://twa-test.github.io"

title: Thoughtworks Arts
twitter_username: tw_arts
author:
  name: Andrew McWilliams
  email: andy@jahya.net
google_analytics: UA-79516906-1

display-banner: false
banner-url: /open-call/2020-synthetic-media/
banner-text: "Open Call: Simulacra & Similitude"

# todo: separate dev and prod env
# future: true
# show_drafts: true
excerpt_separator: <!--excerpt-ends-->

pagination:
  enabled: true
  sort_reverse: true
  collection: posts
  per_page: 7
  permalink: /page:num/

permalink: /blog/:title/
collections:
  projects:
    output: true
    permalink: /projects/:path/
  newsletters:
    output: true
    permalink: /newsletters/:slug/
  people:
    output: true
    permalink: /bio/:path/
  features:
    output: false

defaults:
  - scope:
      type: pages
    values:
      layout    : default
  - scope:
      type: posts
    values:
      layout    : post
      bodyid    : news
  - scope:
      type: newsletters
    values:
      layout    : newsletter
      bodyid    : news
  - scope:
      type: projects
    values:
      layout    : project
      bodyid    : expo
      bodyclass : detail-page
  - scope:
      type: people
    values:
      layout    : bio
      bodyid    : expo
      bodyclass : detail-page bio


plugins:
  - jekyll-feed
  - jekyll-paginate-v2
  - jekyll-sitemap
  - jekyll-redirect-from

sass:
    style: compressed

# todo: check include and exclude
include:
  - .htaccess

exclude:
  - .jekyll-cache/
  - Gemfile
  - Gemfile.lock
